owner: hacktivityconf 
repo: upptime

sites:
  - name: Hacktivity - Tickets
    url: https://tickets.hacktivity.com/en/
  - name: Hacktivity - Website
    url: https://hacktivity.com
    maxResponseTime: 5000
  - name: BSidesBud - CDN
    url: https://cdn.bsidesbud.com/uploads/2017/01/small_logo_website.png
    icon: https://cdn.bsidesbud.com/static/favicon/cficon.png
  - name: BSidesBud - Website
    url: https://bsidesbud.com/sitemap_index.xml
    maxResponseTime: 5000
    headers:
      - "github-bypass: $BSIDESBUD_BYPASS_TOKEN"
  - name: BSidesBud - Analytics
    url: https://t.bsidesbud.com/api/health
    headers:
      - "github-bypass: $BSIDESBUD_BYPASS_TOKEN"
  - name: BSidesBud - Server
    check: "tcp-ping"
    url: $BSIDESBUD_SERVER_IP
    port: $BSIDESBUD_SERVER_PORT
    icon: https://cdn.bsidesbud.com/static/favicon/archicon.png
assignees: 
  - D3vl0per
  - imaro
status-website:
  cname: status.hacktivity.com
  logoUrl: https://cdn.bsidesbud.com/static/favicon/hacktivity-logo_white.png
  favicon: https://cdn.bsidesbud.com/static/favicon/cropped-favicon-32x32.png
  name: Status Page
  introTitle: "Uptime monitoring"
  robotsText: "User-agent: * \n Disallow: /"
  theme: dark
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Hacktivity's Discord
      href: https://discord.hacktvity.com
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
