owner: hacktivityconf 
repo: upptime

sites:
  - name: Hacktivity
    url: https://hacktivity.com
  - name: BSidesBud - CDN
    url: https://cdn.bsidesbud.com/uploads/2017/01/small_logo_website.png
assignees: 
  - D3vl0per
  - imaro
status-website:
  cname: status.hacktivity.com
  logoUrl: https://hacktivity.com/wp-content/uploads/2023/05/hacktivity-logo_white.png
  favicon: https://hacktivity.com/wp-content/uploads/2023/05/cropped-favicon-32x32.png
  name: Status Page
  introTitle: "Uptime monitoring"
  robotsText: "User-agent: * \n Disallow: /"
  theme: dark
  user-agent: Upptime/mLNCswJvolUYm29ckfJAy7MMi7f2hz1C
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Hacktivity's Discord
      href: https://discord.hacktvity.com
    - title: BSidesBud's Discord
      href: https://discord.bsidesbud.com
