owner: hacktivityconf 
repo: upptime

sites:
  - name: Hacktivity
    url: https://hacktivity.com
  - name: BSidesBud - Website
    url: https://bsidesbud.com/sitemap_index.xml
    maxResponseTime: 5000
  - name: BSidesBud - Analytics
    url: https://t.bsidesbud.com
  - name: BSidesBud - CDN
    url: https://cdn.bsidesbud.com/uploads/2017/01/small_logo_website.png
assignees: 
  - D3vl0per
  - imaro
status-website:
  cname: status.hacktivity.com
  logoUrl: https://cdn.bsidesbud.com/uploads/2024/12/bsidesbud_logo_transparent-e1736242572952.png
  favicon: https://cdn.bsidesbud.com/uploads/2024/12/icon-150x150.png
  name: Infrastructure Status Page
  introTitle: "Uptime monitoring"
  robotsText: "User-agent: * \n Disallow: /"
  theme: dark
  user-agent: Upptime/mLNCswJvolUYm29ckfJAy7MMi7f2hz1C
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Hacktivity's Discord
      href: https://discord.hacktvity.com
    - title: BSidesBud's Discord
      href: https://discord.bsidesbud.com
